---
- name: Ansible 1
  hosts: all
  become: true


  tasks:
  - name: create groups
    ansible.builtin.group:
      name: "{{ item }}"
    loop: 
      - "Sales"
      - "Support"
      - "Services"
      - "IT"

  - name: create users
    ansible.builtin.user:
      name: "{{ item['name'] }}"
      password: "@#FD12"
      groups: "{{ item['group'] }}"
      ssh_key_file: ssh_key.pub
    loop:
      - name: "Annabelle"
        group: "Sales"

      - name: "Bob"
        group: "IT"

      - name: "Carl"
        group: "Support"
    
      - name: "Dyson"
        group: "Support"

      - name: "Evert"
        group: "IT"

      - name: "Frank"
        group: "Sales"

      - name: "Gerry"
        group: "Support"

      - name: "Harold"
        group: "IT"

      - name: "Isabella"
        group: "Services"

      - name: "Jameson"
        group: "Services"
